# Generated by Django 3.0.4 on 2020-06-10 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instag', '0002_auto_20200610_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='caption',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
