# Generated by Django 3.0.4 on 2020-06-11 17:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('instag', '0003_post_caption'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dp', models.ImageField(null=True, upload_to='post_images')),
                ('nfollowers', models.IntegerField()),
                ('nfollowing', models.IntegerField()),
                ('nposts', models.IntegerField()),
                ('follows', models.ManyToManyField(related_name='followed_by', to='instag.Profile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='comment',
            name='commentby',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instag.Profile'),
        ),
        migrations.AlterField(
            model_name='like',
            name='likedby',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instag.Profile'),
        ),
        migrations.AlterField(
            model_name='post',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instag.Profile'),
        ),
    ]
