# Generated by Django 3.0.4 on 2020-06-11 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instag', '0004_auto_20200611_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='nc',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='nl',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='nfollowers',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='nfollowing',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='nposts',
            field=models.IntegerField(default=0),
        ),
    ]
