# Generated by Django 3.0.4 on 2020-06-12 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instag', '0007_auto_20200612_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='commentby',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instag.Profile'),
        ),
        migrations.AlterField(
            model_name='like',
            name='likedby',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instag.Profile'),
        ),
        migrations.AlterField(
            model_name='post',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instag.Profile'),
        ),
    ]
