# Generated by Django 3.0.4 on 2020-06-13 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instag', '0009_auto_20200612_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='dp',
            field=models.ImageField(default='dp.png', null=True, upload_to='post_images'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='follows',
            field=models.ManyToManyField(blank=True, related_name='followed_by', to='instag.Profile'),
        ),
    ]
