# Generated by Django 3.0.4 on 2020-06-18 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instag', '0011_auto_20200618_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='dp',
            field=models.ImageField(blank=True, default='dp.png', null=True, upload_to='post_images'),
        ),
    ]
