# Generated by Django 3.0.4 on 2020-06-23 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instag', '0012_auto_20200618_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='full_name',
            field=models.CharField(default=None, max_length=25),
        ),
    ]
