# Generated by Django 3.2.2 on 2022-07-09 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instag', '0016_alter_profile_dp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='dp',
            field=models.ImageField(blank=True, default='post_images/dp.png', null=True, upload_to='post_images'),
        ),
    ]
